SELECT DISTINCT t1.PAT_ID,
                t1.PAT_ENC_CSN_ID,
                t2.DEPARTMENT_NAME,
                t3.NAME as ADT_EVENT_TYPE,
                t1.EFFECTIVE_TIME,
                t4.NAME as PAT_SERVICE_NAME
	   FROM EDW_SOURCE_ZONE_CLARITY.CLINICAL.CLARITY_ADT as t1
	   left join EDW_SOURCE_ZONE_CLARITY.COMMON.CLARITY_DEP as t2 on t1.DEPARTMENT_ID = t2.DEPARTMENT_ID
	   left join EDW_SOURCE_ZONE_CLARITY.COMMON.ZC_EVENT_TYPE as t3 on t1.EVENT_TYPE_C = t3.EVENT_TYPE_C
	   left join EDW_SOURCE_ZONE_CLARITY.COMMON.ZC_PAT_SERVICE as t4 on t1.PAT_SERVICE_C = t4.HOSP_SERV_C
       where t1.EVENT_TYPE_C in (1, 2, 3, 4) 
       and t1.PAT_ENC_CSN_ID in (3745999141) 
       ORDER BY PAT_ID, PAT_ENC_CSN_ID, EFFECTIVE_TIME